Check for binary file warning and don't print
chshersh/github-tui pull request #11
Opened 2024-11-19 01:20 UTC by heathhenley

What do you think about something like this handle the first part of #8 ? 

I originally tried to use external utils to get the type ('file --mime` on unix), and that worked nicely but there doesn't seem to be a nice way to do it on windows so I switched to just looking for the bat warning.

I don't know what the ideal way to handle where the regex pattern / warning text, eg whether it's ocaml'y to stick them at the top level of if they should be somewhere else (in the function? factored into some config somewhere, etc).

New to ocaml and was looking at this project for as an example of how to make a tui - thanks for sharing it!

2024-11-19 01:24 UTC, heathhenley commented
here's what it looks like: 
![image](https://github.com/user-attachments/assets/5ebf4c38-32b7-44b3-b8d8-d0837e32ad09)

2024-11-20 19:54 UTC, chshersh commented
Hey @heathhenley,

Apologies, overlooked your contribution earlier! 🙏🏻 

I'll look into the patch but thanks a ton for looking into this problem!

P.S. Thanks for the kind words about the project 💛

2024-11-21 15:26 UTC, heathhenley commented
I don't have formatting / linting set up locally, probably should for the future anyway so I'll look at getting that set up and fixing the format so that will pass CI. I'm not sure why the opam install should be failing on ci? I only added str in lib/fs/dune 🤷‍♂️

2024-11-23 11:42 UTC, chshersh commented
> I don't have formatting / linting set up locally, probably should for the future anyway so I'll look at getting that set up and fixing the format so that will pass CI

Don't worry about that for now! Once I do #4, it should be trivial to install all required tooling with one command.

> I'm not sure why the opam install should be failing on ci? I only added str in lib/fs/dune 🤷‍♂️

The error is mysterious indeed. I haven't touched this project in 5 months, and software is quite vulnerable to bitrot, unfortunately. I'll try to fix CI in a separate PR, so this PR can be rebased afterwards.

2024-12-21 10:05 UTC, chshersh commented
@heathhenley FYI, I haven't forgot about your PR! Even though, I got side-tracked by other projects, like **FULLY REWRITING MY WEBSITE** and also writing an article on category theory.

I attempted to fix the CI for this project in:

- #12 

But looks like it still doesn't work, and I feel like I'm blocked by:

- https://github.com/leostera/minttea/pull/59

2024-12-21 18:28 UTC, heathhenley commented
Thanks for the note! 

I think I also bumped into that issue with minttea in a separate project. I was trying to use the latest but couldn't get it set it up properly, I ended up just using the previous version (0.0.2) that's on opam (I was starting from scratch so I didn't matter, just had to follow the 0.0.2 tag's conventions versus the latest). Not sure if you're already using new stuff in this project, but I see >=0.0.2 so maybe pinning it to minttea 0.0.2 and whatever riot that uses solves the build issue here?

You probably saw this but I think this is a similar issue going on: https://github.com/leostera/minttea/issues/58

2024-12-21 19:09 UTC, chshersh commented
@heathhenley You're not wrong. I originally bumped into that issue, then I had to figure out pins, and then this new issue.

Well, if you depend on the dev unstable version of a project, you'll get unstable results 😅

I know the maintainer is busy

I do, however, need to use the latest version as I rely on some patches around configuring FPS. I guess, we'll have to wait!

2025-01-07 18:51 UTC, chshersh requested changes
Amazing stuff, @heathhenley! Apologies for the delay, I got busy with side quests but now I'm fully back to this project.

I did some work on fixing CI issues in #13. It's merged, so you should be able to sync with the latest version in main and it should work now.

The implementation looks good to me, I left only a few minor comments.

2025-01-07 18:51 UTC, chshersh commented on lib/fs/fs.ml
> +let binary_file_pattern = Str.regexp ".*\\[bat warning\\].*Binary.*content*."
So, I did some research on this.

Turns out, there's no robust way to check if the file is binary! Tool like `git` use different heuristics like checking the first N bytes if they contain BOM marker or non-printable characters.

In this context, it's absolutely fine to rely on `[bat warning]` even though it's a bit fragile. But this can always be improved later. But lets expand the comment in the spirit "No robust way to check if the file is binary. Improve when becomes a problem".

2025-01-07 18:51 UTC, chshersh commented on lib/fs/dune
> +  str
Lol, I was sincerely surprised to learn that OCaml doesn't have a string search function, and one need to use regular expressions.

Oh, well.

2025-01-07 18:51 UTC, chshersh commented on lib/fs/fs.ml
> +  | _ ->
Let's use `if-then-else` here. I think there's no need to use a match for simple boolean condition

2025-01-07 22:43 UTC, heathhenley commented on lib/fs/fs.ml
> +let binary_file_pattern = Str.regexp ".*\\[bat warning\\].*Binary.*content*."
Nice, that's what I thought too it seems like it can get a little complicated if you want it to be robust. I improved the comment as you recommended in the latest commit

2025-01-07 22:45 UTC, heathhenley commented on lib/fs/fs.ml
> +  | _ ->
Done! I moved the check of the has_binary_warning into a function that just takes contents, I don't know if you prefer that or to just inline it in the if statement, but it feels more readable to me to have that

2025-01-07 22:45 UTC, heathhenley commented
Just pushed an update, lmk what you think!

2025-01-08 17:39 UTC, chshersh commented on lib/fs/fs.ml
> +let binary_file_pattern = Str.regexp ".*\\[bat warning\\].*Binary.*content*."
Thanks for updating the comment!

2025-01-08 17:39 UTC, chshersh commented on lib/fs/fs.ml
> +  | _ ->
Even better! Thanks!

2025-01-08 17:40 UTC, chshersh approved these changes
Looks great! 🏆 

I'll merge once CI passes.

2025-01-08 17:43 UTC, merged